<?php
	define("VERSION", 0.1);
	header("Content-Type: text/xml");
	require("./wp-config.php");
	mysql_connect(DB_HOST, DB_USER, DB_PASSWORD);
	mysql_select_db(DB_NAME);
	$t = $table_prefix;

	$result = mysql_query("
		SELECT `option_value`
		FROM `".$t."options`
		WHERE `option_name`='home'
		LIMIT 1
	");
	$data = mysql_fetch_assoc($result);
	$home = $data['option_value']."/";

	$result = mysql_query("
		SELECT `option_value`
		FROM `".$t."options`
		WHERE `option_name`='ksm_active'
		LIMIT 1
	");
	$data = mysql_fetch_assoc($result);
	$active = $data['option_value'];

	$result = mysql_query("
		SELECT `post_modified`
		FROM `".$t."posts`
		WHERE
			(`post_type`='page' OR `post_type`='post')
			AND `post_status`='publish'
		ORDER BY `post_modified` DESC
		LIMIT 1
	");
	$data = mysql_fetch_assoc($result);
	$homeLastUpdate = $data['post_modified'];
	$homeLastUpdate = substr($homeLastUpdate, 0, 10);

	$result = mysql_query("
		SELECT
			`".$t."posts`.`ID`, `".$t."posts`.`post_modified`, `".$t."posts`.`post_name`,
			`".$t."comments`.`comment_ID`, `".$t."comments`.`comment_post_ID`, `".$t."comments`.`comment_date`
		FROM `".$t."posts`
		LEFT JOIN `".$t."comments` ON `".$t."posts`.`ID`=`".$t."comments`.`comment_post_ID`
		WHERE
			(`".$t."posts`.`post_type`='page' OR `".$t."posts`.`post_type`='post')
			AND `".$t."posts`.`post_status`='publish'
			AND (`".$t."comments`.`comment_approved`='1' OR `".$t."comments`.`comment_approved` IS NULL)
		GROUP BY `".$t."posts`.`ID`
		ORDER BY
			`".$t."posts`.`post_modified` DESC,
			`".$t."comments`.`comment_date` DESC
	");

	echo '<?xml version="1.0" encoding="UTF-8"?>';
?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<!-- Generated by Karailiev's sitemap <?=VERSION?> plugin -->
	<!-- http://www.karailiev.net/ -->
	<?=!$active?"<!-- Plugin is off. Showing only homepage. -->":""?>
	<url>
		<loc><?=$home?></loc>
		<lastmod><?=$homeLastUpdate?></lastmod>
		<changefreq>weekly</changefreq>
		<priority>1.0</priority>
	</url>
<?php
	if ($active) {
		while ($data = mysql_fetch_assoc($result)) {
?>
	<url>
		<loc><?=$home."?p=".$data['ID']?></loc>
		<lastmod><?=substr($data['post_modified'], 0, 10)?></lastmod>
		<changefreq>weekly</changefreq>
		<priority>0.3</priority>
	</url>
<?php
		}
	}
?>
</urlset>